version: '3.9'

services:
  keycloak:
    image: jboss/keycloak
    volumes:
      # No linux o volume já tem que existir senão dá erro, pois ele cria
      # com as permissões erradas
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
    ports:
      - 8081:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  api:
    depends_on:
      - keycloak
    build: .
    ports:
      - 8001:8000
    environment:
      - KEYCLOAK_IP=keycloak
      # a porta do host pode mudar, mas a da rede interna não precisa
      - KEYCLOAK_PORT=8080
      - KEYCLOAK_REALM=master
