version: '3.9'

services:
  keycloak:
    image: jboss/keycloak
    volumes:
      - ./keycloak-data:/opt/jboss/keycloak/standalone/data
    ports:
      - 8082:8080
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
  api:
    depends_on:
      - keycloak
    build: .
    ports:
      - 8001:8000
    environment:
      - KEYCLOAK_IP=keycloak
      - KEYCLOAK_PORT=8082
      - KEYCLOAK_REALM=master
