GET http://localhost:8000 HTTP/1.1

###

GET http://localhost:8000/docs HTTP/1.1

###

GET http://localhost:8000/users/ HTTP/1.1

###
POST http://localhost:8000/classes HTTP/1.1
Content-Type: application/json

{
  "year": "2022",
  "semester": "1",
  "class_number": "31"
}

###
GET http://localhost:8000/turmas HTTP/1.1
Content-Type: application/json

###
POST http://localhost:8000/alunos HTTP/1.1
Content-Type: application/json

{
  "nome": "Kevin",
  "matricula": "16204042"
}

###

GET http://localhost:8000/alunos HTTP/1.1

###
POST http://localhost:8000/horarios HTTP/1.1
Content-Type: application/json

{
  "hora": "N",
  "dia_semana": "segunda"
}

###

GET http://localhost:8000/horarios HTTP/1.1